# Generated by Django 6.1 on 2026-09-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Emp_ID', models.CharField(max_length=100)),
                ('Designation', models.CharField(max_length=100)),
                ('Date_of_Joining', models.DateField()),
                ('Department', models.CharField(max_length=100)),
                ('Annual_CTC', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Student_Name', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=1000)),
            ],
        ),
    ]
