# Generated by Django 6.1 on 2026-09-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmngt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Occasion', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
