# Generated by Django 6.1 on 2026-09-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmngt', '0002_calender_delete_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Details', models.TextField(max_length=1000)),
            ],
        ),
    ]
