# Generated by Django 6.1 on 2026-09-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empmngt', '0003_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=100)),
                ('Skills', models.CharField(max_length=100)),
                ('CTC', models.CharField(max_length=100)),
                ('Notice_Period', models.CharField(max_length=100)),
            ],
        ),
    ]
